/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica;

/**
 *
 * @author Mariana M
 */
public class Formularioprincipal extends javax.swing.JFrame {

    public String nombreUsuaruio;
    public String tipoUsuaruio;

    public Formularioprincipal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        editable = new javax.swing.JInternalFrame();
        bvnusuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRegistrar = new javax.swing.JMenu();
        registrar = new javax.swing.JMenuItem();
        mnuMatricular = new javax.swing.JMenu();
        itmMatricular = new javax.swing.JMenuItem();
        mnuMostrar = new javax.swing.JMenu();
        mostrarAdmin = new javax.swing.JMenuItem();
        mostrarProfesores = new javax.swing.JMenuItem();
        mostrarEstudiantes = new javax.swing.JMenuItem();
        mostrarInvitados = new javax.swing.JMenuItem();
        mostrarUsuarios = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenu();
        eliminarAdmin = new javax.swing.JMenuItem();
        eliminarProfesor = new javax.swing.JMenuItem();
        eliminarEstudiantes = new javax.swing.JMenuItem();
        eliminarInvitados = new javax.swing.JMenuItem();
        mnuModificar = new javax.swing.JMenu();
        modificarAdmin = new javax.swing.JMenuItem();
        modificarProfesor = new javax.swing.JMenuItem();
        modificarEstudiantes = new javax.swing.JMenuItem();
        modificarInvitados = new javax.swing.JMenuItem();
        mnuCambiarpsw = new javax.swing.JMenu();
        cambiarClave = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editable.setVisible(true);

        bvnusuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 75)); // NOI18N
        bvnusuario.setForeground(new java.awt.Color(0, 153, 153));
        bvnusuario.setText(nombreUsuaruio);

        javax.swing.GroupLayout editableLayout = new javax.swing.GroupLayout(editable.getContentPane());
        editable.getContentPane().setLayout(editableLayout);
        editableLayout.setHorizontalGroup(
            editableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bvnusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        editableLayout.setVerticalGroup(
            editableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editableLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(bvnusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        mnuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario.png"))); // NOI18N
        mnuRegistrar.setText("Registrar usuarios");

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        mnuRegistrar.add(registrar);

        jMenuBar1.add(mnuRegistrar);

        mnuMatricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/matricular.png"))); // NOI18N
        mnuMatricular.setText("Matricular ");

        itmMatricular.setText("Ver profesores");
        itmMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMatricularActionPerformed(evt);
            }
        });
        mnuMatricular.add(itmMatricular);

        jMenuBar1.add(mnuMatricular);

        mnuMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrar.png"))); // NOI18N
        mnuMostrar.setText("Mostrar Usuarios");

        mostrarAdmin.setText("Administradores");
        mostrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAdminActionPerformed(evt);
            }
        });
        mnuMostrar.add(mostrarAdmin);

        mostrarProfesores.setText("Profesores");
        mostrarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarProfesoresActionPerformed(evt);
            }
        });
        mnuMostrar.add(mostrarProfesores);

        mostrarEstudiantes.setText("Estudiantes");
        mostrarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEstudiantesActionPerformed(evt);
            }
        });
        mnuMostrar.add(mostrarEstudiantes);

        mostrarInvitados.setText("Invitados");
        mostrarInvitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarInvitadosActionPerformed(evt);
            }
        });
        mnuMostrar.add(mostrarInvitados);

        mostrarUsuarios.setText("Todos los usuarios");
        mostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarUsuariosActionPerformed(evt);
            }
        });
        mnuMostrar.add(mostrarUsuarios);

        jMenuBar1.add(mnuMostrar);

        mnuEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        mnuEliminar.setText("Eliminar");

        eliminarAdmin.setText("Administradores");
        eliminarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAdminActionPerformed(evt);
            }
        });
        mnuEliminar.add(eliminarAdmin);

        eliminarProfesor.setText("Profesores");
        eliminarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProfesorActionPerformed(evt);
            }
        });
        mnuEliminar.add(eliminarProfesor);

        eliminarEstudiantes.setText("Estudiantes");
        eliminarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEstudiantesActionPerformed(evt);
            }
        });
        mnuEliminar.add(eliminarEstudiantes);

        eliminarInvitados.setText("Invitados");
        eliminarInvitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarInvitadosActionPerformed(evt);
            }
        });
        mnuEliminar.add(eliminarInvitados);

        jMenuBar1.add(mnuEliminar);

        mnuModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        mnuModificar.setText("Modificar");

        modificarAdmin.setText("Administradores");
        modificarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAdminActionPerformed(evt);
            }
        });
        mnuModificar.add(modificarAdmin);

        modificarProfesor.setText("Profesores");
        modificarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProfesorActionPerformed(evt);
            }
        });
        mnuModificar.add(modificarProfesor);

        modificarEstudiantes.setText("Estudiantes");
        modificarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEstudiantesActionPerformed(evt);
            }
        });
        mnuModificar.add(modificarEstudiantes);

        modificarInvitados.setText("Invitados");
        modificarInvitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarInvitadosActionPerformed(evt);
            }
        });
        mnuModificar.add(modificarInvitados);

        jMenuBar1.add(mnuModificar);

        mnuCambiarpsw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clave.png"))); // NOI18N
        mnuCambiarpsw.setText("Cambiar contraseña");

        cambiarClave.setText("Cambiar mi contraseña");
        cambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClaveActionPerformed(evt);
            }
        });
        mnuCambiarpsw.add(cambiarClave);

        jMenuBar1.add(mnuCambiarpsw);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editable)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editable)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAdminActionPerformed
        Eliminar eliminar = new Eliminar();
        editable.setContentPane(eliminar);

    }//GEN-LAST:event_eliminarAdminActionPerformed

    private void modificarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAdminActionPerformed
        Modificar modificar = new Modificar();
        editable.setContentPane(modificar);
    }//GEN-LAST:event_modificarAdminActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        bvnusuario.setVisible(false);
         
        if (tipoUsuaruio == "Profesor")
        {
            Registro registro = new Registro(tipoUsuaruio);
            editable.setContentPane(registro);
        } else
        {
            Registro registro = new Registro();
            editable.setContentPane(registro);
        }
        

    }//GEN-LAST:event_registrarActionPerformed

    private void itmMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMatricularActionPerformed
        Matricular matricula = new Matricular();
        editable.setContentPane(matricula);
    }//GEN-LAST:event_itmMatricularActionPerformed

    private void mostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarUsuariosActionPerformed
        Mostrar mostrar = new Mostrar();
        editable.setContentPane(mostrar);
    }//GEN-LAST:event_mostrarUsuariosActionPerformed

    private void mostrarInvitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarInvitadosActionPerformed
        Mostrar mostrar = new Mostrar();
        editable.setContentPane(mostrar);
    }//GEN-LAST:event_mostrarInvitadosActionPerformed

    private void mostrarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEstudiantesActionPerformed
        Mostrar mostrar = new Mostrar();
        editable.setContentPane(mostrar);
    }//GEN-LAST:event_mostrarEstudiantesActionPerformed

    private void mostrarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarProfesoresActionPerformed
        Mostrar mostrar = new Mostrar();
        editable.setContentPane(mostrar);
    }//GEN-LAST:event_mostrarProfesoresActionPerformed

    private void mostrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAdminActionPerformed
        Mostrar mostrar = new Mostrar();
        editable.setContentPane(mostrar);
    }//GEN-LAST:event_mostrarAdminActionPerformed

    private void modificarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProfesorActionPerformed
        Modificar modificar = new Modificar();
        editable.setContentPane(modificar);
    }//GEN-LAST:event_modificarProfesorActionPerformed

    private void modificarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEstudiantesActionPerformed
        Modificar modificar = new Modificar();
        editable.setContentPane(modificar);
    }//GEN-LAST:event_modificarEstudiantesActionPerformed

    private void modificarInvitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarInvitadosActionPerformed
        Modificar modificar = new Modificar();
        editable.setContentPane(modificar);
    }//GEN-LAST:event_modificarInvitadosActionPerformed

    private void eliminarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProfesorActionPerformed
        Eliminar eliminar = new Eliminar();
        editable.setContentPane(eliminar);
    }//GEN-LAST:event_eliminarProfesorActionPerformed

    private void eliminarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEstudiantesActionPerformed
        Eliminar eliminar = new Eliminar();
        editable.setContentPane(eliminar);
    }//GEN-LAST:event_eliminarEstudiantesActionPerformed

    private void eliminarInvitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarInvitadosActionPerformed
        Eliminar eliminar = new Eliminar();
        editable.setContentPane(eliminar);
    }//GEN-LAST:event_eliminarInvitadosActionPerformed

    private void cambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarClaveActionPerformed
        Cambiarcontrasena cambiar = new Cambiarcontrasena();
        editable.setContentPane(cambiar);
    }//GEN-LAST:event_cambiarClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Formularioprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Formularioprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Formularioprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Formularioprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formularioprincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bvnusuario;
    private javax.swing.JMenuItem cambiarClave;
    private javax.swing.JInternalFrame editable;
    public javax.swing.JMenuItem eliminarAdmin;
    private javax.swing.JMenuItem eliminarEstudiantes;
    public javax.swing.JMenuItem eliminarInvitados;
    public javax.swing.JMenuItem eliminarProfesor;
    private javax.swing.JMenuItem itmMatricular;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuCambiarpsw;
    public javax.swing.JMenu mnuEliminar;
    public javax.swing.JMenu mnuMatricular;
    private javax.swing.JMenu mnuModificar;
    private javax.swing.JMenu mnuMostrar;
    public javax.swing.JMenu mnuRegistrar;
    public javax.swing.JMenuItem modificarAdmin;
    public javax.swing.JMenuItem modificarEstudiantes;
    public javax.swing.JMenuItem modificarInvitados;
    public javax.swing.JMenuItem modificarProfesor;
    public javax.swing.JMenuItem mostrarAdmin;
    public javax.swing.JMenuItem mostrarEstudiantes;
    public javax.swing.JMenuItem mostrarInvitados;
    public javax.swing.JMenuItem mostrarProfesores;
    public javax.swing.JMenuItem mostrarUsuarios;
    private javax.swing.JMenuItem registrar;
    // End of variables declaration//GEN-END:variables
}
